name: Pull Reqest Workflow

on:
  workflow_dispatch:
  pull_request:
    branches: [ "master" ]

jobs:        
  system-test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Make Gradle Wrapper script executable
      run: chmod +x ./gradlew

    - name: Build with Gradle
      uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
      with:
        arguments: build

    - name: Run jar
      run: java -jar build/libs/devops-final-0.0.1-SNAPSHOT.jar &
        
    - name: Run System Test
      run: ./gradlew systemTest
        
